"""Story director: pacing control, story threads, and event injection."""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field

from jag.agents.llm import LLMProvider
from jag.core.events import EventBus, EventType, GameEvent
from jag.world.world import WorldState

logger = logging.getLogger(__name__)


class StoryBeatModel(BaseModel):
    """A story beat generated by the director."""

    event_type: str = Field(default="world", description="Type: world, social, quest, environment")
    description: str = Field(default="", description="What happens")
    source_id: str = Field(default="", description="Source entity")
    location_id: str = Field(default="", description="Where it happens")
    importance: int = Field(default=5, description="Importance 1-10")
    data: dict[str, Any] = Field(default_factory=dict, description="Additional data")


@dataclass
class StoryThread:
    """A story thread that spans multiple events."""

    id: str
    title: str
    description: str = ""
    status: str = "active"  # active, climax, resolved, dormant
    events: list[str] = field(default_factory=list)  # event IDs
    involved_entities: list[str] = field(default_factory=list)
    turns_active: int = 0
    turns_since_event: int = 0


STORY_DIRECTOR_PROMPT = """你是一个开放世界RPG的故事导演。
你的职责是分析当前游戏状态和最近的事件，决定是否有故事发展应该发生。
所有输出内容请使用简体中文。

故事发展类型：
- 升级：现有局势恶化
- 揭示：发现新信息
- 机遇：出现新的可能性
- 后果：过去的行为产生反作用
- 邂逅：意外的会面或发现

考虑因素：
- 玩家参与度（不要让事情变得无聊）
- 叙事连贯性（事件应该合理）
- 世界一致性（尊重已建立的世界）
- 节奏控制（动作与安静时刻交替）

只在有有意义的发展时才生成故事节拍。
每回合最多返回 0-2 个节拍。
"""


class StoryDirector:
    """Analyze game state and inject story developments.

    Features:
    - Pacing analysis: inject events when things are too quiet
    - Thread management: track and develop ongoing story threads
    - Interest inference: adapt to player behavior patterns
    """

    def __init__(
        self,
        llm: LLMProvider | None = None,
        event_bus: EventBus | None = None,
        pacing_threshold: int = 5,
    ) -> None:
        self.llm = llm
        self.event_bus = event_bus
        self.pacing_threshold = pacing_threshold
        self.threads: dict[str, StoryThread] = {}
        self._turns_without_event = 0
        self._player_interests: dict[str, int] = {}  # category -> count

    def create_thread(
        self, title: str, description: str = "", entities: list[str] | None = None
    ) -> StoryThread:
        """Create a new story thread."""
        thread_id = f"thread_{uuid.uuid4().hex[:8]}"
        thread = StoryThread(
            id=thread_id,
            title=title,
            description=description,
            involved_entities=entities or [],
        )
        self.threads[thread_id] = thread
        return thread

    def get_active_threads(self) -> list[StoryThread]:
        """Get all active story threads."""
        return [t for t in self.threads.values() if t.status in ("active", "climax")]

    async def process(
        self, events: list[GameEvent], world: WorldState
    ) -> list[dict[str, Any]]:
        """Process events and generate story developments.

        Returns list of story beat dicts.
        """
        # Track pacing
        if events:
            self._turns_without_event = 0
            self._analyze_player_interests(events)
        else:
            self._turns_without_event += 1

        # Update thread turn counters
        for thread in self.threads.values():
            if thread.status == "active":
                thread.turns_active += 1
                thread.turns_since_event += 1

        story_beats: list[dict[str, Any]] = []

        # LLM-based story generation
        if self.llm and (events or self._turns_without_event >= self.pacing_threshold):
            try:
                beats = await self._llm_story(events, world)
                story_beats.extend(beats)
            except Exception as e:
                logger.warning("LLM story generation failed: %s", e)

        # Rule-based pacing injection
        if not story_beats and self._turns_without_event >= self.pacing_threshold:
            beats = self._pacing_injection(world)
            story_beats.extend(beats)

        # Publish story events
        if self.event_bus:
            for beat in story_beats:
                evt_type_map = {
                    "world": EventType.WORLD,
                    "social": EventType.SOCIAL,
                    "quest": EventType.QUEST,
                    "environment": EventType.ENVIRONMENT,
                }
                await self.event_bus.publish(
                    GameEvent(
                        event_type=evt_type_map.get(beat.get("event_type", "world"), EventType.WORLD),
                        source_id=beat.get("source_id", ""),
                        location_id=beat.get("location_id", ""),
                        description=beat.get("description", ""),
                        data={**beat, "_story": True},
                        turn=world.time.turn,
                    )
                )

        return story_beats

    async def _llm_story(
        self, events: list[GameEvent], world: WorldState
    ) -> list[dict[str, Any]]:
        """Generate story beats via LLM."""
        assert self.llm is not None

        recent_events = "\n".join(
            f"- {e.description} ({e.event_type.value})" for e in events[-10:]
        ) or "(No recent events)"

        active_threads = "\n".join(
            f"- [{t.status}] {t.title}: {t.description} ({t.turns_active} turns)"
            for t in self.get_active_threads()
        ) or "(No active story threads)"

        interests = ", ".join(
            f"{k}({v})" for k, v in sorted(
                self._player_interests.items(), key=lambda x: -x[1]
            )[:5]
        ) or "unknown"

        prompt = (
            f"World State: Turn {world.time.turn}, "
            f"{world.time.time_of_day()}, Day {world.time.day}, {world.time.season}\n"
            f"Locations: {len(world.locations)}, Characters: {len(world.characters)}\n\n"
            f"Recent Events:\n{recent_events}\n\n"
            f"Active Story Threads:\n{active_threads}\n\n"
            f"Player Interests: {interests}\n\n"
            f"Quiet turns: {self._turns_without_event}\n\n"
            f"Generate 0-2 meaningful story developments."
        )

        response = await self.llm.complete(
            prompt=prompt,
            system=STORY_DIRECTOR_PROMPT,
        )

        # Parse response into beats (simple extraction)
        beats: list[dict[str, Any]] = []
        if response and response.strip():
            beats.append({
                "event_type": "world",
                "description": response.strip(),
                "source_id": "story_director",
                "location_id": "",
                "importance": 7,
                "data": {"origin": "llm"},
            })

        return beats

    def _pacing_injection(self, world: WorldState) -> list[dict[str, Any]]:
        """Inject a pacing event when things are too quiet."""
        import random

        rng = random.Random(world.time.turn)
        location_ids = list(world.locations.keys())
        if not location_ids:
            return []

        loc_id = rng.choice(location_ids)
        location = world.locations[loc_id]

        templates = [
            {
                "event_type": "environment",
                "description": f"一阵奇异的声音在{location.name}回荡。",
                "source_id": "ambient",
                "location_id": loc_id,
                "importance": 3,
            },
            {
                "event_type": "social",
                "description": f"一位旅行者来到{location.name}，带来了远方的消息。",
                "source_id": "traveler",
                "location_id": loc_id,
                "importance": 5,
            },
            {
                "event_type": "world",
                "description": f"{location.name}附近有什么不寻常的东西引起了你的注意。",
                "source_id": "discovery",
                "location_id": loc_id,
                "importance": 4,
            },
        ]

        beat = rng.choice(templates)
        beat["data"] = {"origin": "pacing"}
        self._turns_without_event = 0
        return [beat]

    def _analyze_player_interests(self, events: list[GameEvent]) -> None:
        """Track player interests based on their actions."""
        for event in events:
            category = event.event_type.value
            self._player_interests[category] = self._player_interests.get(category, 0) + 1
